version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: manga-backend-dev
    ports:
      - "3012:3012"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - redis
      - postgres
    command: pnpm --filter backend dev

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: manga-frontend-dev
    env_file:
      - frontend/.env
    ports:
      - "3011:3011"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    command: pnpm --filter frontend dev

  redis:
    image: redis:7-alpine
    container_name: manga-redis-dev
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: manga-postgres-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
