version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: manga-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    restart: unless-stopped

volumes:
  redis_data:
