FROM node:20-slim

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package files
COPY .npmrc ./
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./
COPY tsconfig.json ./
COPY backend/package.json ./backend/

RUN apt-get update -y && apt-get install -y openssl

# Install all dependencies
RUN pnpm install --filter backend...
