/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xKKUiu6JBfU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { LIMIT } from "@/app/[id]/page";
import Link from "next/link";
import { useEffect } from "react";
import CustomPagination from "./Pagination/pagination";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Toggle } from "./ui/toggle";

export function ChapterList({
  chapters,
  page,
  setPage,
  total,
  setChaptersToDownloadFrom,
  chaptersToDownloadFrom,
  handleSubmitDownload,
  setIsToggled,
  isToggled,
  mangaId,
  downloadChapter,
}) {
  console.log(chapters);

  const pageNumbers = [];
  const totalPages = Math.ceil(total / LIMIT);
  let numberOfChapters = 0;
  while (chapters[numberOfChapters]?.attributes.chapter) {
    numberOfChapters++;
  }
  console.log(numberOfChapters);

  // if (totalPages <= 5) {
  //   for (let i = 1; i <= totalPages; i++) {
  //     pageNumbers.push(i);
  //   }
  // } else {
  //   console.log(page, totalPages);
  //   if (page > 3 && page < totalPages - 2) {
  //     pageNumbers.push(1, "...", page - 1, page, page + 1, "...", totalPages);
  //   } else if (page > 3 && page === totalPages - 1) {
  //     pageNumbers.push(1, "...", totalPages - 2, totalPages - 1, totalPages);
  //   } else if (page > 3 && page === totalPages - 2) {
  //     pageNumbers.push(1, "...", page - 1, page, page + 1, page + 2);
  //   } else if (page > 3 && page === totalPages) {
  //     pageNumbers.push(1, "...", totalPages - 1, totalPages);
  //   } else if (page === 3) {
  //     pageNumbers.push(1, "...", 2, 3, 4, "...", totalPages);
  //   } else {
  //     pageNumbers.push(1, 2, 3, "...", totalPages);
  //   }
  // }

  useEffect(() => {
    console.log(isToggled);
  }, [isToggled]);

  return (
    <div className="container mx-auto px-4 py-8 md:px-6 md:py-12">
      <div className="mb-6 md:mb-8 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold md:text-3xl">Manga Chapters</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Browse through the latest chapters.
          </p>
        </div>
        <Toggle
          pressed={isToggled}
          onPressedChange={() => setIsToggled(!isToggled)}
        >
          Downloaded Chapters
        </Toggle>
      </div>
      <div className="mb-6 flex items-center gap-2">
        <label
          htmlFor="download-from"
          className="text-gray-500 dark:text-gray-400"
        >
          Download chapters from:
        </label>
        <Input
          id="download-from"
          type="number"
          placeholder="From"
          className="w-20"
          onChange={(e) =>
            setChaptersToDownloadFrom({
              ...chaptersToDownloadFrom,
              from: e.target.value,
            })
          }
        />
        <span className="text-gray-500 dark:text-gray-400">to</span>
        <Input
          id="download-to"
          type="number"
          placeholder="To"
          className="w-20"
          onChange={(e) =>
            setChaptersToDownloadFrom({
              ...chaptersToDownloadFrom,
              to: e.target.value,
            })
          }
        />
        <Button variant="outline" onClick={handleSubmitDownload}>
          Validate
        </Button>
      </div>
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        {chapters &&
          chapters.map((chapter) => {
            return (
              <>
                <Link
                  href={`/${mangaId}/chapter/${chapter.id}/1`}
                  id={chapter.attributes.id}
                  className="bg-white rounded-lg shadow-md dark:bg-gray-800"
                >
                  <div className="p-4 min-w-14">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">
                        Chapter {chapter.attributes.chapter}
                      </span>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">
                        {chapter.attributes.pages} pages
                      </span>
                    </div>
                    <h3 className="text-lg font-semibold mb-2">
                      {chapter.attributes.title}
                    </h3>
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        Volume {chapter.attributes.volume}
                      </span>
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        {new Date(
                          chapter.attributes.publishAt
                        ).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                  <button
                    className="w-full py-2 bg-primary-500 text-gray-500 font-semibold "
                    onClick={() => {
                      downloadChapter(chapter.attributes.chapter);
                    }}
                  >
                    Download
                  </button>
                </Link>
              </>
            );
          })}
      </div>
      <CustomPagination page={page} setPage={setPage} totalPages={totalPages} />
      {/* <div className="flex justify-center mt-8">
        <Pagination>
          <PaginationContent>
            {page > 1 && (
              <PaginationItem>
                <PaginationPrevious
                  href="#"
                  onClick={() => {
                    if (page !== 1) setPage(page - 1);
                  }}
                />
              </PaginationItem>
            )}
            {pageNumbers.map((number, index) => (
              <PaginationItem key={index}>
                <PaginationLink
                  href="#"
                  isActive={number === page}
                  onClick={() => typeof number === "number" && setPage(number)}
                >
                  {number}
                </PaginationLink>
              </PaginationItem>
            ))}
            {page < totalPages && (
              <PaginationItem>
                <PaginationNext
                  aria-disabled={true}
                  onClick={() => {
                    setPage(page + 1);
                  }}
                  href="#"
                />
              </PaginationItem>
            )}
          </PaginationContent>
        </Pagination>
      </div> */}
    </div>
  );
}
