/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xKKUiu6JBfU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';
import { Button } from '@/app/components/ui/button';
import { Input } from '@/app/components/ui/input';
import Link from 'next/link';
import CustomPagination from './Pagination/pagination';

const LIMIT = 24;

interface Chapter {
  id: string;
  attributes: {
    chapter: string;
    title: string;
    volume: string;
    pages: number;
    publishAt: string;
    id: string;
  };
}

interface ChaptersToDownload {
  from: string | number;
  to: string | number;
}

interface ChapterListProps {
  chapters: Chapter[];
  page: number;
  setPage: (page: number) => void;
  total: number;
  setChaptersToDownloadFrom: (chapters: ChaptersToDownload) => void;
  chaptersToDownloadFrom: ChaptersToDownload;
  handleSubmitDownload: () => void;
  mangaId: string;
  downloadChapter: (chapter: string) => void;
  setChapter: (chapters: Chapter[]) => void;
}

export function ChapterList({
  chapters,
  page,
  setPage,
  total,
  setChaptersToDownloadFrom,
  chaptersToDownloadFrom,
  handleSubmitDownload,
  mangaId,
  downloadChapter,
  setChapter,
}: ChapterListProps) {
  const totalPages = Math.ceil(total / LIMIT);
  let numberOfChapters = 0;
  while (chapters[numberOfChapters]?.attributes.chapter) {
    numberOfChapters++;
  }

  return (
    <div className="container mx-auto px-4 py-8 md:px-6 md:py-12">
      <div className="mb-6 md:mb-8">
        <h1 className="text-2xl font-bold md:text-3xl">Manga Chapters</h1>
        <p className="text-gray-500 dark:text-gray-400">Browse through the latest chapters.</p>
      </div>
      <div className="mb-6 flex items-center gap-2">
        <label htmlFor="download-from" className="text-gray-500 dark:text-gray-400">
          Download chapters from:
        </label>
        <Input
          id="download-from"
          type="number"
          placeholder="From"
          className="w-20"
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setChaptersToDownloadFrom({
              ...chaptersToDownloadFrom,
              from: e.target.value,
            })
          }
        />
        <span className="text-gray-500 dark:text-gray-400">to</span>
        <Input
          id="download-to"
          type="number"
          placeholder="To"
          className="w-20"
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setChaptersToDownloadFrom({
              ...chaptersToDownloadFrom,
              to: e.target.value,
            })
          }
        />
        <Button variant="outline" onClick={handleSubmitDownload}>
          Validate
        </Button>
      </div>
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        {chapters &&
          chapters.map((chapter: Chapter) => {
            return (
              <>
                <Link
                  href={`/${mangaId}/chapter/${chapter.id}/1`}
                  id={chapter.attributes.id}
                  className="bg-white rounded-lg shadow-md dark:bg-gray-800"
                >
                  <div className="p-4 min-w-14">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">
                        Chapter {chapter.attributes.chapter}
                      </span>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">
                        {chapter.attributes.pages} pages
                      </span>
                    </div>
                    <h3 className="text-lg font-semibold mb-2">{chapter.attributes.title}</h3>
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        Volume {chapter.attributes.volume}
                      </span>
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        {new Date(chapter.attributes.publishAt).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                  <button
                    className="w-full py-2 bg-primary-500 text-gray-500 font-semibold "
                    onClick={() => {
                      downloadChapter(chapter.attributes.chapter);
                    }}
                  >
                    Download
                  </button>
                </Link>
              </>
            );
          })}
      </div>
      <CustomPagination page={page} setPage={setPage} totalPages={totalPages} />
    </div>
  );
}
